/* ============================================================================
   Case Files — 20 real-world analytics scenarios (PRD section 8). Metadata
   here; the full guide-style brief lives in public/cases/<id>.md and is fetched
   as a static asset. Downloadable CSV datasets sit in
   public/cases/data/<id>/ and are generated by scripts/gen-case-data.mjs.

   Difficulty: ROOKIE | ANALYST | SENIOR. Dataset size scales with it —
   ROOKIE ~1-5k rows, ANALYST ~5-20k, SENIOR 20k+.
   ========================================================================== */

export type Difficulty = "ROOKIE" | "ANALYST" | "SENIOR";

export interface CaseDataset {
  /** filename under public/cases/data/<id>/ */
  file: string;
  rows: number;
  /** honest heads-up about the state of this file */
  quality: string;
}

export interface CaseDef {
  id: string; // "case-01"
  num: string; // "01"
  title: string;
  industry: string;
  difficulty: Difficulty;
  /** curriculum node ids this case exercises */
  skills: string[];
  /** the tool this case is written for */
  tool: string;
  /** true once a real brief exists in public/cases/<id>.md */
  written: boolean;
  /** downloadable CSVs in public/cases/data/<id>/ */
  datasets?: CaseDataset[];
}

export const CASES: CaseDef[] = [
  {
    id: "case-01", num: "01", title: "Retail Sales Audit", industry: "Retail", difficulty: "ROOKIE",
    skills: ["excel", "pivot-tables"], tool: "Excel or Google Sheets", written: true,
    datasets: [
      { file: "transactions.csv", rows: 4612, quality: "lightly dirty — a few blank prices, some misspelled store names, scattered 0-unit rows" },
    ],
  },
  {
    id: "case-02", num: "02", title: "Social Media Engagement Report", industry: "Media", difficulty: "ROOKIE",
    skills: ["excel", "charts"], tool: "Excel or Google Sheets", written: true,
    datasets: [
      { file: "posts.csv", rows: 1460, quality: "clean — but 'reach' is blank for the first two months (tracking wasn't set up yet)" },
    ],
  },
  {
    id: "case-03", num: "03", title: "Restaurant Revenue by Location", industry: "Hospitality", difficulty: "ROOKIE",
    skills: ["excel", "pivot-tables"], tool: "Excel or Google Sheets", written: true,
    datasets: [
      { file: "tickets.csv", rows: 6603, quality: "lightly dirty — some tips recorded as negative, a few tickets with no location" },
    ],
  },
  {
    id: "case-04", num: "04", title: "SQL Customer Order Analysis", industry: "E-commerce", difficulty: "ROOKIE",
    skills: ["sql", "select-from", "where", "group-having"], tool: "SQLite (load the 3 CSVs as tables)", written: true,
    datasets: [
      { file: "customers.csv", rows: 600, quality: "mostly clean — but region doesn't always match city" },
      { file: "orders.csv", rows: 2627, quality: "clean" },
      { file: "order_items.csv", rows: 5187, quality: "clean — a handful of negative unit prices" },
    ],
  },
  {
    id: "case-05", num: "05", title: "Fintech Churn Analysis", industry: "Fintech", difficulty: "ANALYST",
    skills: ["sql", "joins", "aggregates"], tool: "SQLite", written: true,
    datasets: [
      { file: "users.csv", rows: 5000, quality: "clean" },
      { file: "transactions.csv", rows: 160514, quality: "clean — a cluster of users go silent after a specific app version" },
    ],
  },
  {
    id: "case-06", num: "06", title: "Logistics Route Efficiency", industry: "Logistics", difficulty: "ANALYST",
    skills: ["sql", "visualization"], tool: "SQLite + a chart tool", written: true,
    datasets: [
      { file: "deliveries.csv", rows: 14000, quality: "dirty — duplicate delivery IDs, some arrival before dispatch" },
    ],
  },
  {
    id: "case-07", num: "07", title: "E-commerce Funnel Drop", industry: "E-commerce", difficulty: "ANALYST",
    skills: ["visualization", "python"], tool: "Python (pandas) or SQLite", written: true,
    datasets: [
      { file: "events.csv", rows: 25155, quality: "clean — but one device type stops firing the 'payment' event mid-month" },
    ],
  },
  {
    id: "case-08", num: "08", title: "Hospital Readmission Patterns", industry: "Healthcare", difficulty: "ANALYST",
    skills: ["statistics", "python"], tool: "Python (pandas)", written: true,
    datasets: [
      { file: "admissions.csv", rows: 12000, quality: "clean — but discharge time is missing for weekend discharges" },
    ],
  },
  {
    id: "case-09", num: "09", title: "Telecom Customer Segments", industry: "Telecom", difficulty: "ANALYST",
    skills: ["python", "statistics"], tool: "Python (pandas)", written: true,
    datasets: [
      { file: "subscribers.csv", rows: 15000, quality: "lightly dirty — tenure_months has a few impossible values (>50 years)" },
    ],
  },
  {
    id: "case-10", num: "10", title: "Real Estate Price Trends", industry: "Real Estate", difficulty: "ANALYST",
    skills: ["python", "visualization"], tool: "Python (pandas)", written: true,
    datasets: [
      { file: "listings.csv", rows: 9000, quality: "dirty — price and area both have outliers; some 'sold' dates before 'listed' dates" },
    ],
  },
  {
    id: "case-11", num: "11", title: "HR Attrition Analysis", industry: "Corporate", difficulty: "ANALYST",
    skills: ["power-bi", "excel"], tool: "Power BI (or Excel)", written: true,
    datasets: [
      { file: "employees.csv", rows: 3200, quality: "clean" },
      { file: "exits.csv", rows: 285, quality: "clean — exit_reason is free text and inconsistent" },
    ],
  },
  {
    id: "case-12", num: "12", title: "EdTech Completion Rate Drop", industry: "EdTech", difficulty: "ANALYST",
    skills: ["storytelling", "sql"], tool: "SQLite + a slide", written: true,
    datasets: [
      { file: "enrolments.csv", rows: 20000, quality: "clean" },
      { file: "lesson_progress.csv", rows: 100881, quality: "clean — one lesson's completion drops off a cliff after a content update" },
    ],
  },
  {
    id: "case-13", num: "13", title: "Ride-hailing Driver Efficiency", industry: "Mobility", difficulty: "ANALYST",
    skills: ["sql", "window-ranking"], tool: "SQLite", written: true,
    datasets: [
      { file: "trips.csv", rows: 30000, quality: "lightly dirty — a few trips with 0 distance but non-zero fare" },
    ],
  },
  {
    id: "case-14", num: "14", title: "Retail Inventory Shrinkage", industry: "Retail", difficulty: "ANALYST",
    skills: ["sql", "excel"], tool: "SQLite or Excel", written: true,
    datasets: [
      { file: "stock_movements.csv", rows: 18028, quality: "clean — but the counted stock and the expected stock diverge at one store" },
    ],
  },
  {
    id: "case-15", num: "15", title: "SaaS Cohort Retention", industry: "SaaS", difficulty: "SENIOR",
    skills: ["sql", "real-world-patterns"], tool: "SQLite", written: true,
    datasets: [
      { file: "accounts.csv", rows: 8000, quality: "clean" },
      { file: "subscription_events.csv", rows: 13920, quality: "clean — pause events are recorded but easy to mistake for churn" },
    ],
  },
  {
    id: "case-16", num: "16", title: "Supply Chain Delay Tracker", industry: "Manufacturing", difficulty: "SENIOR",
    skills: ["sql", "power-bi"], tool: "SQLite + Power BI", written: true,
    datasets: [
      { file: "purchase_orders.csv", rows: 26000, quality: "dirty — supplier names not standardised, some promised dates in the past" },
    ],
  },
  {
    id: "case-17", num: "17", title: "Bank Transaction Anomaly Detection", industry: "Banking", difficulty: "SENIOR",
    skills: ["python", "statistics"], tool: "Python (pandas)", written: true,
    datasets: [
      { file: "transactions.csv", rows: 90000, quality: "clean — a small set of accounts show a structuring pattern (many just-under-threshold transfers)" },
    ],
  },
  {
    id: "case-18", num: "18", title: "Insurance Claims Pattern", industry: "Insurance", difficulty: "SENIOR",
    skills: ["statistics", "python"], tool: "Python (pandas)", written: true,
    datasets: [
      { file: "claims.csv", rows: 32583, quality: "lightly dirty — some claim amounts are strings with currency symbols" },
    ],
  },
  {
    id: "case-19", num: "19", title: "Marketplace Take-rate Analysis", industry: "SaaS", difficulty: "SENIOR",
    skills: ["sql", "python"], tool: "SQLite + Python", written: true,
    datasets: [
      { file: "orders.csv", rows: 55000, quality: "clean — but the fee column was calculated wrong for one seller tier" },
    ],
  },
  {
    id: "case-20", num: "20", title: "Portfolio Capstone", industry: "Open", difficulty: "SENIOR",
    skills: ["portfolio"], tool: "Your choice — pick one and defend it", written: true,
  },
];

export const CASES_BY_ID: Record<string, CaseDef> = Object.fromEntries(CASES.map((c) => [c.id, c]));

export const DIFFICULTY_ACCENT: Record<Difficulty, string> = {
  ROOKIE: "var(--accent-3)",
  ANALYST: "var(--accent-1)",
  SENIOR: "var(--primary)",
};
