/* ============================================================================
   The PM's morning lines. One per day, never repeated for a given learner
   (tracked in localStorage). Dry, a little mean, invested underneath. No em
   dashes, same voice as the system prompt.
   ========================================================================== */
export interface Quote {
  id: string;
  text: string;
}

export const QUOTES: Quote[] = [
  { id: "q001", text: "Morning. The data didn't clean itself overnight. I checked." },
  { id: "q002", text: "Good morning. Yesterday's analysis is still yesterday's analysis. Today needs its own." },
  { id: "q003", text: "You're here. That's the low bar cleared. Now the real one." },
  { id: "q004", text: "Morning. A dashboard nobody reads is just a screensaver with opinions." },
  { id: "q005", text: "Good morning. Correlation still isn't causation. It wasn't over the weekend either." },
  { id: "q006", text: "Morning. The number is only as good as the question you asked to get it." },
  { id: "q007", text: "Up early, or up late? Either way, open the file." },
  { id: "q008", text: "Good morning. Nobody was ever fired for checking the join twice." },
  { id: "q009", text: "Morning. If the chart needs a paragraph to explain it, the chart lost." },
  { id: "q010", text: "Good morning. Your future self is going to read this query. Be kind to them." },
  { id: "q011", text: "Morning. 'The data looks fine' is a feeling, not a finding." },
  { id: "q012", text: "Good morning. Half of analysis is noticing the thing that shouldn't be there." },
  { id: "q013", text: "Morning. A spreadsheet with 40 tabs is a cry for help." },
  { id: "q014", text: "Good morning. The stakeholder wants a decision, not a tour of your methodology." },
  { id: "q015", text: "Morning. Average is where insight goes to hide." },
  { id: "q016", text: "Good morning. You can't fix data you haven't looked at." },
  { id: "q017", text: "Morning. Every 'quick pull' takes an hour. Plan accordingly." },
  { id: "q018", text: "Good morning. If you're surprised by the result, good. Now find out why." },
  { id: "q019", text: "Morning. Nulls are not zeros. Say it until it stops biting you." },
  { id: "q020", text: "Good morning. The best analysts are the most suspicious people in the room." },
  { id: "q021", text: "Morning. A finding you can't explain to your aunt isn't finished." },
  { id: "q022", text: "Good morning. You will spend more time on the data than on the analysis. Make peace with it." },
  { id: "q023", text: "Morning. 'It's probably an outlier' is the start of an investigation, not the end." },
  { id: "q024", text: "Good morning. The pie chart with nine slices was a dare and you should not have taken it." },
  { id: "q025", text: "Morning. Rename the column. 'sum_2' will haunt you in three months." },
  { id: "q026", text: "Good morning. If the deadline moved up, the scope moves down. That is the deal." },
  { id: "q027", text: "Morning. Show me the query or it didn't happen." },
  { id: "q028", text: "Good morning. Reproducible beats impressive." },
  { id: "q029", text: "Morning. The person who documents the weird bit is the person who gets thanked later." },
  { id: "q030", text: "Good morning. You're not behind. You're just not done. Different problem." },
  { id: "q031", text: "Morning. A trend over three points is a mood, not a trend." },
  { id: "q032", text: "Good morning. Sort the column. You'll see it in two seconds instead of twenty minutes." },
  { id: "q033", text: "Morning. If two dashboards disagree, at least one of them is lying to someone." },
  { id: "q034", text: "Good morning. The interesting number is the one that doesn't fit." },
  { id: "q035", text: "Morning. 'I'll remember what this filter does' is a lie you tell yourself." },
  { id: "q036", text: "Good morning. Precision to four decimals on a rough estimate is just showing off." },
  { id: "q037", text: "Morning. The hard part was never the SQL. It was knowing which SQL to write." },
  { id: "q038", text: "Good morning. Clean the data, then clean it again. It's not clean." },
  { id: "q039", text: "Morning. A good analyst asks 'compared to what' before anything else." },
  { id: "q040", text: "Good morning. Your gut is a hypothesis generator, not a conclusion." },
  { id: "q041", text: "Morning. If you're copying numbers by hand, stop. There is a better way and you know it." },
  { id: "q042", text: "Good morning. The report is due when it's right, but 'right' has a deadline too." },
  { id: "q043", text: "Morning. Nobody remembers the analysis. They remember the one number you got wrong." },
  { id: "q044", text: "Good morning. A dashboard is a product. It has users. Treat it like one." },
  { id: "q045", text: "Morning. When the total doesn't match, the total is right and your logic is wrong. Usually." },
  { id: "q046", text: "Good morning. You learn more from the analysis that surprised you than the ten that didn't." },
  { id: "q047", text: "Morning. Filter first, aggregate second. In that order, every time." },
  { id: "q048", text: "Good morning. 'Statistically significant' and 'matters' are two different meetings." },
  { id: "q049", text: "Morning. The chart is for them, not for you. Design it that way." },
  { id: "q050", text: "Good morning. If you can't say what would change your mind, you're not analysing, you're defending." },
  { id: "q051", text: "Morning. Every dataset has a story about how it was collected. Learn it before you trust it." },
  { id: "q052", text: "Good morning. The junior who says 'I don't understand this column' is doing the job." },
  { id: "q053", text: "Morning. A model you can't explain is a liability with good manners." },
  { id: "q054", text: "Good morning. Save the raw file. Always keep a copy of the raw file." },
  { id: "q055", text: "Morning. 'Roughly' is a fine answer if you say how roughly." },
  { id: "q056", text: "Good morning. The dashboard loads slowly because you asked it to scan a billion rows on every click. Fix the query." },
  { id: "q057", text: "Morning. You don't need a bigger tool. You need a smaller question." },
  { id: "q058", text: "Good morning. Two hours of thinking saves two days of querying." },
  { id: "q059", text: "Morning. The stakeholder's question and the stakeholder's actual problem are rarely the same thing." },
  { id: "q060", text: "Good morning. If the finding makes the person who asked look bad, deliver it anyway. Kindly, but anyway." },
  { id: "q061", text: "Morning. A comment that explains 'why' is worth ten that explain 'what'." },
  { id: "q062", text: "Good morning. You can be fast or you can be first-time-right. Pick the second one until you've earned the first." },
  { id: "q063", text: "Morning. The outlier you delete without checking is the fraud you missed." },
  { id: "q064", text: "Good morning. 'The system says so' is not a source." },
  { id: "q065", text: "Morning. Group by the thing, not by the thing plus a typo of the thing." },
  { id: "q066", text: "Good morning. Every 'final_v2_actualfinal.xlsx' is a monument to poor version control." },
  { id: "q067", text: "Morning. Write down the assumption. You will forget you made it." },
  { id: "q068", text: "Good morning. A confident wrong answer costs more than an honest 'I need a day'." },
  { id: "q069", text: "Morning. The trend line is a suggestion. The residuals are the story." },
  { id: "q070", text: "Good morning. If the ask is 'just a number', ask what decision the number feeds. There's always a decision." },
  { id: "q071", text: "Morning. You are one week from being annoyed at code you wrote today. Format it now." },
  { id: "q072", text: "Good morning. Percentages need a denominator. State it or don't use them." },
  { id: "q073", text: "Morning. The dashboard that answers one question well beats the one that answers twelve badly." },
  { id: "q074", text: "Good morning. When in doubt, plot it. Your eyes catch things your summary stats miss." },
  { id: "q075", text: "Morning. 'It worked yesterday' means the data changed. Go find out how." },
  { id: "q076", text: "Good morning. The analyst who tests the edge case is the analyst who sleeps well." },
  { id: "q077", text: "Morning. A finding without a recommendation is homework, not work." },
  { id: "q078", text: "Good morning. You're allowed to not know. You're not allowed to guess and call it knowing." },
  { id: "q079", text: "Morning. The join that returns more rows than you started with is trying to tell you something." },
  { id: "q080", text: "Good morning. Excel will happily let you sort one column and not the others. Excel is not your friend today." },
  { id: "q081", text: "Morning. Round at the end. Never in the middle." },
  { id: "q082", text: "Good morning. The best chart type is usually a bar chart. Sorry." },
  { id: "q083", text: "Morning. 'The numbers speak for themselves' is what people say right before they misread the numbers." },
  { id: "q084", text: "Good morning. Check the date range. It's always the date range." },
  { id: "q085", text: "Morning. A dashboard nobody's opened in 90 days is not a dashboard. It's a cost." },
  { id: "q086", text: "Good morning. If you're not a little embarrassed by last month's work, you haven't learned anything." },
  { id: "q087", text: "Morning. The question 'is this normal' has no answer until you define normal." },
  { id: "q088", text: "Good morning. Timezones have ended more analyses than bad SQL ever did." },
  { id: "q089", text: "Morning. You can automate the pull or you can do it by hand every Monday forever. Your call." },
  { id: "q090", text: "Good morning. A stakeholder who says 'make it pop' means 'I don't trust the numbers'. Fix the trust." },
  { id: "q091", text: "Morning. The first cut is always wrong. That's why it's called the first cut." },
  { id: "q092", text: "Good morning. Read the whole brief. The answer to your question is in the part you skipped." },
  { id: "q093", text: "Morning. 'Directionally correct' is a phrase for when you didn't check." },
  { id: "q094", text: "Good morning. Segment it. The aggregate is hiding at least one thing you'd want to know." },
  { id: "q095", text: "Morning. You will be judged by the one slide, not the forty in the appendix. Make the one slide count." },
  { id: "q096", text: "Good morning. If the growth chart starts the y-axis at 90, someone is trying to sell you something." },
  { id: "q097", text: "Morning. Ask 'who told you that' at least once a day. It's a load-bearing question." },
  { id: "q098", text: "Good morning. The data engineer is not the enemy. The data engineer is the person who knows why the column is null." },
  { id: "q099", text: "Morning. A pivot table is a fold over a grouped index. Now it's less scary." },
  { id: "q100", text: "Good morning. You don't finish learning SQL. You just get faster at looking things up." },
  { id: "q101", text: "Morning. The report said 'up 200%'. From two to six. Context is a courtesy, provide it." },
  { id: "q102", text: "Good morning. Your job is to be wrong in private so the company is right in public." },
  { id: "q103", text: "Morning. If the analysis took ten minutes, spend ten more checking it. It's still faster than being wrong." },
  { id: "q104", text: "Good morning. 'Let me get back to you' beats a made-up number every single time." },
  { id: "q105", text: "Morning. The interesting question is rarely the one they asked. It's the one next to it." },
  { id: "q106", text: "Good morning. Every dataset is a photograph of a moment someone decided to measure. Ask why that moment." },
  { id: "q107", text: "Morning. You're going to hit a bug that isn't your fault. Fix it anyway, then tell someone." },
  { id: "q108", text: "Good morning. A tidy table now is an hour you don't lose later. Compound interest, basically." },
  { id: "q109", text: "Morning. The chart critic in your head is right more often than you'd like. Listen to them before you ship." },
  { id: "q110", text: "Good morning. Nobody starts good at this. They start stubborn. You've got that part." },
  { id: "q111", text: "Morning. Two things are true: the deadline is real, and rushing the join will cost you the day. Plan around both." },
  { id: "q112", text: "Good morning. If you can't reproduce it, you can't defend it. And someone will make you defend it." },
  { id: "q113", text: "Morning. The dashboard is done when you can't remove anything else, not when you can't add anything." },
  { id: "q114", text: "Good morning. Your first instinct on the weird number is usually right. Your second-guessing is usually the mistake." },
  { id: "q115", text: "Morning. 'The client is always right' is for waiters. You're paid to tell them when the data says otherwise." },
];
